//! Configuration (`docs/design-mint.md` § *Mint configuration*). v1 is
//! single-tenant, single-root-key.
//!
//! Audience, tenant, and role metadata are file-backed (TOML); the
//! macaroon root key is not config (generated by [`crate::state::Store`]
//! at `<data_dir>/root_key`). Each role's IAM-policy template lives in
//! its own file under
//! `roles_dir`, named by the role's `policy_file` (a single normal path
//! component — see [`read_policy`]). The Tigris admin credential is the
//! one input that comes from the environment — `AWS_*`, resolved by
//! [`AdminCredential::from_env`] at load — never the TOML, so secrets
//! and role definitions stay on separate management planes.

use std::collections::BTreeMap;
use std::path::{Component, Path, PathBuf};

use serde::Deserialize;

#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    #[error("read config: {0}")]
    Io(#[from] std::io::Error),
    #[error("parse config: {0}")]
    Toml(#[from] toml::de::Error),
    #[error("duplicate role name: {0}")]
    DuplicateRole(String),
    #[error("role {role}: {field} must be > 0 and min <= default <= max")]
    BadTtlBounds { role: String, field: String },
    #[error(
        "role {role}: policy_file {value:?} must be a single filename \
         (no path separators, no '.' or '..', not absolute)"
    )]
    BadPolicyFileName { role: String, value: String },
    #[error(
        "role {role}: derived policy filename {value:?} is not a single \
         filename — set an explicit policy_file or rename the role"
    )]
    BadDerivedPolicyName { role: String, value: String },
    #[error("role {role}: read policy_file {path}: {source}")]
    ReadPolicyFile {
        role: String,
        path: String,
        #[source]
        source: std::io::Error,
    },
}

#[derive(Debug, Deserialize)]
pub struct RawConfig {
    /// The audience name this mint answers to. A macaroon whose
    /// `Audience` caveat differs is rejected (cross-service replay
    /// defence).
    pub audience: String,
    /// Directory for mint's persisted state — the macaroon root key
    /// (`root_key`, generated on first start), the current bootstrap
    /// nonce, and the transient pending-enrollment table, all under one
    /// custody (`docs/design-mint.md` § *Enrollment*, § *Mint
    /// configuration*). A relative value
    /// (including the default `mint_data`) resolves against the current
    /// working directory, not the config file's parent — the same rule
    /// the elide coordinator uses for `data_dir`; an absolute path is
    /// used verbatim.
    #[serde(default)]
    pub data_dir: Option<String>,
    /// Directory holding role policy-template files, one per role
    /// (referenced by each role's `policy_file`). Same resolution rule
    /// as `data_dir`; defaults to `mint_roles`.
    #[serde(default)]
    pub roles_dir: Option<String>,
    pub tenant: Tenant,
    #[serde(rename = "role", default)]
    pub roles: Vec<RawRole>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Tenant {
    /// Bucket name; surfaced to templates as `{{tenant.bucket}}`.
    pub bucket: String,
}

/// Tigris admin credential, read from the standard AWS environment
/// variables — the same convention the elide coordinator uses for its
/// IAM-mode admin credential. It is deliberately **not** in the TOML
/// config: the credential is a secret delivered by the environment
/// (systemd `LoadCredential=`, a secrets manager, …), never committed
/// alongside role definitions.
#[derive(Clone)]
pub struct AdminCredential {
    pub access_key_id: String,
    pub secret_access_key: String,
    /// `AWS_SESSION_TOKEN` if present (STS-style temporary creds).
    pub session_token: Option<String>,
}

impl std::fmt::Debug for AdminCredential {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Never render the secret — only that a credential is present.
        f.debug_struct("AdminCredential")
            .field("access_key_id", &self.access_key_id)
            .field("secret_access_key", &"<redacted>")
            .field(
                "session_token",
                &self.session_token.as_ref().map(|_| "<redacted>"),
            )
            .finish()
    }
}

impl AdminCredential {
    /// Resolve from `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY`
    /// (+ optional `AWS_SESSION_TOKEN`). `None` if either required var
    /// is unset or empty — the prototype's faked minter does not need
    /// it, so absence is a warning at startup, not a hard error.
    pub fn from_env() -> Option<Self> {
        let access_key_id = non_empty_env("AWS_ACCESS_KEY_ID")?;
        let secret_access_key = non_empty_env("AWS_SECRET_ACCESS_KEY")?;
        Some(Self {
            access_key_id,
            secret_access_key,
            session_token: non_empty_env("AWS_SESSION_TOKEN"),
        })
    }
}

fn non_empty_env(key: &str) -> Option<String> {
    std::env::var(key).ok().filter(|v| !v.is_empty())
}

#[derive(Debug, Deserialize)]
pub struct RawRole {
    pub name: String,
    #[serde(default)]
    pub required_caveats: Vec<String>,
    pub min_ttl_seconds: u64,
    pub max_ttl_seconds: u64,
    pub default_ttl_seconds: u64,
    /// Filename of the IAM-policy handlebars template (see
    /// [`crate::template`]), resolved against `roles_dir`. Optional;
    /// defaults to `<name>.json`. Whether explicit or derived it must
    /// be a single normal path component — validated by [`read_policy`]
    /// (so a role `name` with a path separator is rejected too).
    #[serde(default)]
    pub policy_file: Option<String>,
}

/// Validated configuration, ready to serve.
#[derive(Debug)]
pub struct Config {
    pub audience: String,
    /// Persisted-state directory: the root key (generated on first
    /// start), bootstrap nonce, and pending table all share this
    /// custody. Defaults to `mint_data` when the config omits
    /// `data_dir`. The root key itself is owned by
    /// [`crate::state::Store`], not parsed from config.
    pub data_dir: PathBuf,
    /// Directory the role `policy_file`s were read from. Defaults to
    /// `mint_roles`. Retained for diagnostics; policies are already
    /// resolved into [`Role::policy`].
    pub roles_dir: PathBuf,
    pub tenant: Tenant,
    /// Resolved from the AWS environment at load time. `None` when the
    /// env is unset (fine for the prototype's faked minter; a real
    /// Tigris minter must check this is `Some`).
    pub admin: Option<AdminCredential>,
    pub roles: BTreeMap<String, Role>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Role {
    pub name: String,
    pub required_caveats: Vec<String>,
    pub min_ttl_seconds: u64,
    pub max_ttl_seconds: u64,
    pub default_ttl_seconds: u64,
    /// The role's IAM-policy handlebars template, read from
    /// `<roles_dir>/<policy_file>` at load.
    pub policy: String,
}

impl Config {
    pub fn from_toml_str(s: &str) -> Result<Config, ConfigError> {
        Self::from_raw(toml::from_str(s)?)
    }

    pub fn load(path: &Path) -> Result<Config, ConfigError> {
        Self::from_toml_str(&std::fs::read_to_string(path)?)
    }

    fn from_raw(raw: RawConfig) -> Result<Config, ConfigError> {
        let roles_dir = raw
            .roles_dir
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("mint_roles"));
        let mut roles = BTreeMap::new();
        for r in raw.roles {
            if r.min_ttl_seconds == 0
                || r.min_ttl_seconds > r.default_ttl_seconds
                || r.default_ttl_seconds > r.max_ttl_seconds
            {
                return Err(ConfigError::BadTtlBounds {
                    role: r.name.clone(),
                    field: "ttl_seconds".into(),
                });
            }
            let policy = match r.policy_file {
                Some(ref f) => read_policy(&roles_dir, &r.name, f, true)?,
                None => read_policy(&roles_dir, &r.name, &format!("{}.json", r.name), false)?,
            };
            let role = Role {
                name: r.name.clone(),
                required_caveats: r.required_caveats,
                min_ttl_seconds: r.min_ttl_seconds,
                max_ttl_seconds: r.max_ttl_seconds,
                default_ttl_seconds: r.default_ttl_seconds,
                policy,
            };
            if roles.insert(r.name.clone(), role).is_some() {
                return Err(ConfigError::DuplicateRole(r.name));
            }
        }
        Ok(Config {
            audience: raw.audience,
            data_dir: raw
                .data_dir
                .map(PathBuf::from)
                .unwrap_or_else(|| PathBuf::from("mint_data")),
            roles_dir,
            tenant: raw.tenant,
            admin: AdminCredential::from_env(),
            roles,
        })
    }
}

/// Read a role's policy template from `<roles_dir>/<policy_file>`.
///
/// `policy_file` is parsed, not substring-checked: `Path::new` of it
/// must yield exactly one [`Component::Normal`]. That rejects path
/// separators, absolute paths, `.`, `..`, parent traversal, and the
/// empty string in one predicate, so a role name cannot reach outside
/// `roles_dir`. The guarantee is name-level — a symlink *inside*
/// `roles_dir` is still followed, but `roles_dir` shares the config's
/// custody, so its contents are the operator's own.
///
/// `explicit` selects the diagnostic: a bad *explicit* `policy_file` is
/// [`ConfigError::BadPolicyFileName`]; a bad *derived* `<name>.json`
/// (i.e. an unsafe role name) is [`ConfigError::BadDerivedPolicyName`].
fn read_policy(
    roles_dir: &Path,
    role: &str,
    policy_file: &str,
    explicit: bool,
) -> Result<String, ConfigError> {
    let mut comps = Path::new(policy_file).components();
    let only = comps.next();
    if comps.next().is_some() || !matches!(only, Some(Component::Normal(_))) {
        let (role, value) = (role.to_owned(), policy_file.to_owned());
        return Err(if explicit {
            ConfigError::BadPolicyFileName { role, value }
        } else {
            ConfigError::BadDerivedPolicyName { role, value }
        });
    }
    let path = roles_dir.join(policy_file);
    std::fs::read_to_string(&path).map_err(|source| ConfigError::ReadPolicyFile {
        role: role.to_owned(),
        path: path.display().to_string(),
        source,
    })
}

/// Path-A test harness (shared with `role.rs`'s unit tests): write each
/// role policy into a tempdir, splice an absolute `roles_dir` into the
/// TOML, then exercise the real [`Config::from_toml_str`] file-read
/// path. The tempdir only needs to outlive the parse — `policy` is read
/// eagerly — so it is dropped on return.
#[cfg(test)]
pub(crate) fn parse_for_test(toml: &str, roles: &[(&str, &str)]) -> Result<Config, ConfigError> {
    let dir = tempfile::tempdir().expect("tempdir");
    for (name, body) in roles {
        std::fs::write(dir.path().join(name), body).expect("write role file");
    }
    let injected = toml.replacen(
        "[tenant]",
        &format!(
            "roles_dir = {:?}\n[tenant]",
            dir.path().display().to_string()
        ),
        1,
    );
    Config::from_toml_str(&injected)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
audience = "mint"

[tenant]
bucket = "demo-bucket"

[[role]]
name = "volume-ro"
required_caveats = ["elide:Volume", "Audience", "NotAfter"]
min_ttl_seconds = 60
max_ttl_seconds = 2592000
default_ttl_seconds = 2592000
policy_file = "volume-ro.json"
"#;

    #[test]
    fn parses_sample() {
        let c = parse_for_test(SAMPLE, &[("volume-ro.json", "{}")]).expect("parse");
        assert_eq!(c.audience, "mint");
        assert_eq!(c.tenant.bucket, "demo-bucket");
        assert_eq!(c.roles["volume-ro"].policy, "{}");
    }

    #[test]
    fn rejects_inverted_ttl_bounds() {
        let bad = SAMPLE.replace("max_ttl_seconds = 2592000", "max_ttl_seconds = 10");
        assert!(matches!(
            parse_for_test(&bad, &[("volume-ro.json", "{}")]),
            Err(ConfigError::BadTtlBounds { .. })
        ));
    }

    #[test]
    fn rejects_policy_file_traversal() {
        // Name validation fires before any read, so roles_dir is never
        // touched — no file is written.
        for evil in ["../escape.json", "/etc/passwd", "a/b.json", "..", "."] {
            let toml = SAMPLE
                .replace("[tenant]", "roles_dir = \"mint_roles\"\n[tenant]")
                .replace("volume-ro.json", evil);
            assert!(
                matches!(
                    Config::from_toml_str(&toml),
                    Err(ConfigError::BadPolicyFileName { .. })
                ),
                "expected BadPolicyFileName for {evil:?}"
            );
        }
    }

    #[test]
    fn rejects_missing_policy_file() {
        let dir = tempfile::tempdir().expect("tempdir");
        let toml = SAMPLE.replace(
            "[tenant]",
            &format!(
                "roles_dir = {:?}\n[tenant]",
                dir.path().display().to_string()
            ),
        );
        assert!(matches!(
            Config::from_toml_str(&toml),
            Err(ConfigError::ReadPolicyFile { .. })
        ));
    }

    #[test]
    fn policy_file_defaults_to_name_json() {
        // Drop the explicit policy_file: it must derive `<name>.json`.
        let toml = SAMPLE.replace("policy_file = \"volume-ro.json\"\n", "");
        let c = parse_for_test(&toml, &[("volume-ro.json", "{}")]).expect("parse");
        assert_eq!(c.roles["volume-ro"].policy, "{}");
    }

    #[test]
    fn unsafe_role_name_rejected_when_derived() {
        // No explicit policy_file, so the unsafe name flows into the
        // derived filename and must be caught — distinctly from an
        // explicit bad policy_file.
        let toml = SAMPLE
            .replace("policy_file = \"volume-ro.json\"\n", "")
            .replace("[tenant]", "roles_dir = \"mint_roles\"\n[tenant]")
            .replace("name = \"volume-ro\"", "name = \"../escape\"");
        assert!(matches!(
            Config::from_toml_str(&toml),
            Err(ConfigError::BadDerivedPolicyName { .. })
        ));
    }
}
